redis:
  image: bitnami/redis:latest
  ports:
    - "6379:6379"
  net: "host"
  environment:
  - REDIS_PASSWORD
  container_name: denguetorpedo-redis

denguetorpedo:
  build: ./denguetorpedo
  ports:
    - "3000:3000"
  command: "./deploy.sh"
  net: "host"
  container_name: denguetorpedo
  environment:
  - DATABASE_URL
  - REDISTOGO_URL
  - S3_BUCKET_NAME
  volumes:
  - /path/to/denguetorpedo:/home/dengue/denguetorpedo