redis:
  build: ./redis
  ports:
    - "6379:6379"
  net: "host"
  env_file: .env
  container_name: denguetorpedo-redis
  volumes:
    - /home/fernando/Documentos/SE2/denguechat-compose/redis
  restart: always

denguetorpedo:
  build: ./denguetorpedo
  ports:
    - "3001:3001"
    - "5000:5000"
  command: "./deploy.sh"
  net: "host"
  container_name: denguetorpedo
  env_file: .env
  volumes:
  - /home/fernando/Documentos/SE2/denguechat-compose
  restart: always
