redis:
  build: ./redis
  ports:
    - "6379:6379"
  net: "host"
  env_file: .env
  container_name: denguetorpedo-redis
  volumes:
    - /home/appcivist/production/denguechat-compose/redis/redisVolume:/bitnami

denguetorpedo:
  build: ./denguetorpedo
  ports:
    - "3001:3001"
  command: "./deploy.sh"
  net: "host"
  container_name: denguetorpedo
  env_file: .env
  volumes:
  - /home/appcivist/production/denguetorpedo:/home/dengue/denguetorpedo
