redis:
  build: ./redis
  expose:
    - "6379"
  ports:
    - "6379:6379"
  env_file: .env
  container_name: denguetorpedo-redis
  volumes:
    - /Users/Alan/Documents/UCA-CYT/SE2/2019/denguechat-compose/redis/redisVolume:/bitnami
  restart: always

denguetorpedo:
  build: ./denguetorpedo
  expose:
    - "3001"
    - "5000"
  ports:
    - "3001:3001"
    - "5000:5000"
  command: "./deploy.sh"
  container_name: denguetorpedo
  env_file: .env
  volumes:
    - /Users/Alan/Documents/UCA-CYT/SE2/2019/denguetorpedo:/home/dengue/denguetorpedo
  # restart: always
  extra_hosts:
    postgreshost: 192.168.0.13 #casalan
    #postgreshost: 172.17.0.2
