redis:
  build: ./redis
  ports:
    - "6379:6379"
  net: "host"
  env_file: .env
  container_name: denguetorpedo-redis
  volumes:
    - redis/redis-volume:/bitnami

denguetorpedo:
  build: ./denguetorpedo
  ports:
    - "3000:3000"
  command: "./deploy.sh"
  net: "host"
  container_name: denguetorpedo
  env_file: .env
  volumes:
  - /home/appcivist/production/denguetorpedo:/home/dengue/denguetorpedo
